language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t vc/frontend_dev -f Dockerfile.dev .

script:
  - docker run -e CI=true --name frontend_container vc/frontend_dev npm run test
